---
title: "Preprocessing Zebrafish Datasets"
author:
- name: Elyas Heidari
  affiliation:
  - Department of Biological Systems Sciences and Engineering, ETH Zurich, Switzerland 
  - IMLS Institute for Molecular Life Sciences, University of Zurich, Switzerland
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
    toc_float: true
    number_sections: false
---

<!-- 2020-04-17 17:13 -->
<!-- elihei  [<eheidari@student.ethz.ch>]-->
<!--/Volumes/Projects/scGCN/analysis/0-preprocessing.Rmd-->



## Setup

```{r setup, include = FALSE}
library('BiocStyle')
knitr::opts_chunk$set(autodep=TRUE, cache=TRUE, dev='png', cache.lazy = FALSE)
# wflow_build(files='analysis/0-preprocessing.Rmd', view=F, verbose=T, delete_cache=F, cache.lazy = FALSE)
```

## Load dependencies
```{r load_packages}
suppressMessages(source('code/R/dep.R'))
```

## Initialization and load data
```{r load_data}
# initialization
tidy_farrell   = 'data_tidy/farrell'
tidy_wagner    = 'data_tidy/wagner'
output_farrell = 'output/farrell'
output_wagner  = 'output/wagner'
# load farrell data
mtx_farrell    = fread(file.path(tidy_farrell, 'count_matrix.txt')) %>% setkey('GENE')
meta_farrell   = fread(file.path(tidy_farrell, 'meta_data.txt')) %>% setkey('barcode')
type_cols      = names(meta_farrell) %>% setdiff(c('', 'barcode', 'Stage', 'Segment'))
meta_farrell[, (type_cols):=lapply(.SD, as.logical), .SDcols = type_cols]
# load wagner data
mtx_wagner     = fread(file.path(tidy_wagner, 'count_matrix.txt')) %>% setkey('GENE')
meta_wagner    = fread(file.path(tidy_wagner, 'meta_data.txt')) %>% setkey('barcode')
```

## Subset datasets
```{r subset_data}
# subset matrices on shared cell types
type_farrell = names(meta_farrell) %>%
    setdiff(c('', 'barcode', 'Stage', 'Segment')) %>%
    str_remove("cephalic.") %>%
    sort %>% 
    str_remove_all('dorsal |ventral |lateral | *anterior *| *posterior *') %>%
    setdiff('') %>%
    sort
type_wagner  = melt(meta_wagner, measure = patterns("type$")) %>%
    .$value %>% 
    str_remove_all('dorsal |ventral |lateral | *anterior *| *posterior *') %>%
    setdiff('') %>%
    sort
abv_farrell  = type_farrell %>% substr(1, 5)
abv_wagner   = type_wagner %>% substr(1, 5)
type_farrell = data.table(type_farrell=type_farrell, abv=abv_farrell) %>% setkey(abv)
type_wagner  = data.table(type_wagner=type_wagner, abv=abv_wagner) %>% setkey(abv)
shared_types = type_wagner[type_farrell, on = 'abv', nomatch=0]
type_farrell = names(meta_farrell) %>% 
    grep(paste(shared_types$type_farrell, collapse='|'), .) %>%
    names(meta_farrell)[.]
type_wagner  = melt(meta_wagner, measure=patterns("type$"))$value %>% setdiff('')
type_wagner  %<>% 
    grep(paste(shared_types$type_wagner, collapse='|'), .) %>%
    type_wagner[.]
## farrell
idx_farrell   = which(rowSums(meta_farrell[, ..type_farrell]) > 0)
cells_farrell = meta_farrell$barcode[idx_farrell]
mtx_farrell   = mtx_farrell[, c('GENE', ..cells_farrell)]
# rm(idx_farrell, cells_farrell)
## wagner
cells_wagner  = meta_wagner[type %in% type_wagner | 
                            subtype %in% type_wagner |
                            subsubtype %in% type_wagner,
                            get('barcode')]
mtx_wagner    = mtx_wagner[, c('GENE', ..cells_wagner)]
# subset matrices on shared genes
shared_genes  = intersect(mtx_wagner$GENE, mtx_farrell$GENE)
mtx_farrell   = mtx_farrell[shared_genes, ]
mtx_wagner    = mtx_wagner[shared_genes, ]
# rm(shared_genes)
gc()
```

## Find shared types
```{r cluster_prop, message=FALSE, warning=FALSE, paged.print=FALSE}
# select shared types based on abreviated names
abv_types    = unique(shared_types$abv)
meta_farrell = meta_farrell[cells_farrell, ]
type_farrell = names(meta_farrell)
abv_farrell  = abv_types %>% 
    map(function(x) grep(x, type_farrell)) %>%
    map(function(x) rowSums(meta_farrell[, ..x])) %>%
    # map(function(x) x > 0) %>% 
    purrr::reduce(cbind) %>%
    data.table %>%
    setnames(abv_types) %>%
    cbind(meta_farrell[, .(barcode, Stage, Segment)], .) %>%
    setkey(barcode)
sel_farrell = which(rowSums(abv_farrell[, -c('barcode', 'Stage', 'Segment')]) == 1)
abv_farrell = abv_farrell[sel_farrell, ]
abv_farrell = melt(abv_farrell[, -c('Segment', 'Stage')], id.vars='barcode')
abv_farrell = abv_farrell[(value > 0)] %>%
    setnames('variable', 'abv_type') %>%
    .[, c('barcode', 'abv_type')]
meta_wagner = meta_wagner[cells_wagner, ]
strx <- function(types){
    types %>% map(function(x) c(na.omit(str_extract(x, abv_types)))[1]) %>% unlist
}
abv_wagner = meta_wagner  %>%
    .[, abv_type:=strx(subsubtype)] %>%
    .[is.na(abv_type), abv_type:= strx(subtype)] %>%
    .[is.na(abv_type), abv_type:= strx(type)] %>%
    .[, c('barcode', 'abv_type')]
# subset cells
## farrell
cells_farrell = unique(abv_farrell$barcode)
mtx_farrell   = mtx_farrell[, c('GENE', ..cells_farrell)]
## wagner
cells_wagner  = abv_wagner$barcode
mtx_wagner    = mtx_wagner[, c('GENE', ..cells_wagner)]
file.path(tidy_farrell, 'abv_types.txt') %>%
    fwrite(abv_farrell, .)
file.path(tidy_wagner, 'abv_types.txt') %>%
    fwrite(abv_wagner, .)
```

## Balance cell type compositions
```{r bal_comp, message=FALSE, warning=FALSE, paged.print=FALSE}
# calculate cell type composition
cmp_farrell = table(abv_farrell$abv_type)
cmp_wagner  = table(abv_wagner$abv_type)
cmp_table   = pmin(cmp_wagner, cmp_farrell)
abv_farrell %<>% .[, .SD[sample(1:dim(.SD)[1], ..cmp_table[abv_type])], by = 'abv_type']
abv_wagner  %<>% .[, .SD[sample(1:dim(.SD)[1], ..cmp_table[abv_type])], by = 'abv_type']
# subset w.r.t compositions
## farrell
cells_farrell = unique(abv_farrell$barcode)
mtx_farrell   = mtx_farrell[, c('GENE', ..cells_farrell)]
## wagner
cells_wagner  = abv_wagner$barcode
mtx_wagner    = mtx_wagner[, c('GENE', ..cells_wagner)]
```

## Select higely variable genes
```{r hvg}
# select higly variable genes
hvg                 = hv_genes(as.matrix(mtx_wagner[, -c('GENE')]), 400)
hvg                 = mtx_wagner[hvg, get('GENE')]
# subset farrell
data_farrell        = t(as.matrix(mtx_farrell[hvg, -c('GENE')]))
## convert farrell to raw
data_farrell = 2^(data_farrell) - 1
colnames(data_farrell) = mtx_farrell[hvg, GENE]
data_farrell %<>% as.data.table
const_cols          = which(colSds(as.matrix(data_farrell)) == 0)
data_farrell %<>% as.data.table() %>% .[, -..const_cols]
# subset wagner
data_wagner         = data.table(t(as.matrix(mtx_wagner[hvg, -c('GENE')])))
names(data_wagner)  = mtx_wagner[hvg, GENE]
```

## Construct GGM, Wagner's {.tabset}


### Wagner, rho = 0.2 {.tabset}

#### Wagner
```{r ggm_wagner_0.2}
rho_wagner = 0.2
# ggm for wagner
ggm_wagner   = ggm(data_wagner, rho=rho_wagner)
# visualize graph
graph_wagner = ggm_wagner$graph
isolated     = which(degree(graph_wagner) == 0)
graph_wagner = delete.vertices(graph_wagner, isolated)
res_wagner   = graph_vis(graph_wagner, plot=T)
title('Wagner et. al.', line=2.5, sub=sprintf('gLasso, rho = %s', rho_wagner))
# save results
## adj matrix
wi_wagner    = ggm_wagner$model$wi %>% .[-isolated, -isolated]
colnames(wi_wagner) = rownames(wi_wagner) = names(V(graph_wagner))
file.path(tidy_wagner, sprintf('wi_adj_%s.txt', rho_wagner)) %>%
    fwrite(wi_wagner, .)
## gene communities
comm_wagner  = res_wagner$communities
comm_wag_dt  = data.table(GENE=names(comm_wagner), community=comm_wagner) %>%
    setkey(community)
file.path(tidy_wagner, sprintf('gene_communities_%s.txt', rho_wagner)) %>%
    fwrite(comm_wag_dt, .)
```

#### Farrell, rho = 0.1
```{r ggm_farrell_0.1_.2}
rho_farrell = 0.1
# ggm for farrell
keep_genes    = names(V(graph_wagner))
ggm_farrell   = ggm(data_farrell[, ..keep_genes], rho=rho_farrell)
graph_farrell = ggm_farrell$graph
isolated      = which(degree(graph_farrell)==0)
graph_farrell = delete.vertices(graph_farrell, isolated)
res_farrell   = graph_vis(graph_farrell, plot=T, groups=res_wagner$communities[-isolated])
title('Farrell et. al.', line=2.5, sub=sprintf('gLasso, rho = %s', rho_farrell))
# save results
## adj matrix
wi_farrell    = ggm_farrell$model$wi %>% .[-isolated, -isolated]
colnames(wi_farrell) = rownames(wi_farrell) = names(V(graph_farrell))
file.path(tidy_farrell, sprintf('wi_adj_%s_%s.txt', rho_farrell, rho_wagner)) %>%
    fwrite(wi_farrell, .)
## gene communities
comm_farrell  = res_farrell$communities
comm_farr_dt  = data.table(GENE=names(comm_farrell), community=comm_farrell) %>%
    setkey(community)
file.path(tidy_farrell, sprintf('gene_communities_%s_%s.txt', rho_farrell, rho_wagner)) %>%
    fwrite(comm_farr_dt, .)
```

#### Farrell, rho = 0.2
```{r ggm_farrell_0.2_.2}
rho_farrell = 0.2
# ggm for farrell
keep_genes    = names(V(graph_wagner))
ggm_farrell   = ggm(data_farrell[, ..keep_genes], rho=rho_farrell)
graph_farrell = ggm_farrell$graph
isolated      = which(degree(graph_farrell)==0)
graph_farrell = delete.vertices(graph_farrell, isolated)
res_farrell   = graph_vis(graph_farrell, plot=T, groups=res_wagner$communities[-isolated])
title('Farrell et. al.', line=2.5, sub=sprintf('gLasso, rho = %s', rho_farrell))
# save results
## adj matrix
wi_farrell    = ggm_farrell$model$wi %>% .[-isolated, -isolated]
colnames(wi_farrell) = rownames(wi_farrell) = names(V(graph_farrell))
file.path(tidy_farrell, sprintf('wi_adj_%s_%s.txt', rho_farrell, rho_wagner)) %>%
    fwrite(wi_farrell, .)
## gene communities
comm_farrell  = res_farrell$communities
comm_farr_dt  = data.table(GENE=names(comm_farrell), community=comm_farrell) %>%
    setkey(community)
file.path(tidy_farrell, sprintf('gene_communities_%s_%s.txt', rho_farrell, rho_wagner)) %>%
    fwrite(comm_farr_dt, .)
```


### Wagner, rho = 0.3 {.tabset}

#### Wagner
```{r ggm_wagner_0.3}
rho_wagner = 0.3
# ggm for wagner
ggm_wagner   = ggm(data_wagner, rho=rho_wagner)
# visualize graph
graph_wagner = ggm_wagner$graph
isolated     = which(degree(graph_wagner) == 0)
graph_wagner = delete.vertices(graph_wagner, isolated)
res_wagner   = graph_vis(graph_wagner, plot=T)
title('Wagner et. al.', line=2.5, sub=sprintf('gLasso, rho = %s', rho_wagner))
# save results
## adj matrix
wi_wagner    = ggm_wagner$model$wi %>% .[-isolated, -isolated]
colnames(wi_wagner) = rownames(wi_wagner) = names(V(graph_wagner))
file.path(tidy_wagner, sprintf('wi_adj_%s.txt', rho_wagner)) %>%
    fwrite(wi_wagner, .)
## gene communities
comm_wagner  = res_wagner$communities
comm_wag_dt  = data.table(GENE=names(comm_wagner), community=comm_wagner) %>%
    setkey(community)
file.path(tidy_wagner, sprintf('gene_communities_%s.txt', rho_wagner)) %>%
    fwrite(comm_wag_dt, .)
```

#### Farrell, rho = 0.1
```{r ggm_farrell_0.1_.3}
rho_farrell = 0.1
# ggm for farrell
keep_genes    = names(V(graph_wagner))
ggm_farrell   = ggm(data_farrell[, ..keep_genes], rho=rho_farrell)
graph_farrell = ggm_farrell$graph
isolated      = which(degree(graph_farrell)==0)
graph_farrell = delete.vertices(graph_farrell, isolated)
res_farrell   = graph_vis(graph_farrell, plot=T, groups=res_wagner$communities[-isolated])
title('Farrell et. al.', line=2.5, sub=sprintf('gLasso, rho = %s', rho_farrell))
# save results
## adj matrix
wi_farrell    = ggm_farrell$model$wi %>% .[-isolated, -isolated]
colnames(wi_farrell) = rownames(wi_farrell) = names(V(graph_farrell))
file.path(tidy_farrell, sprintf('wi_adj_%s_%s.txt', rho_farrell, rho_wagner)) %>%
    fwrite(wi_farrell, .)
## gene communities
comm_farrell  = res_farrell$communities
comm_farr_dt  = data.table(GENE=names(comm_farrell), community=comm_farrell) %>%
    setkey(community)
file.path(tidy_farrell, sprintf('gene_communities_%s_%s.txt', rho_farrell, rho_wagner)) %>%
    fwrite(comm_farr_dt, .)
```

#### Farrell, rho = 0.2
```{r ggm_farrell_0.2_.3}
rho_farrell = 0.2
# ggm for farrell
keep_genes    = names(V(graph_wagner))
ggm_farrell   = ggm(data_farrell[, ..keep_genes], rho=rho_farrell)
graph_farrell = ggm_farrell$graph
isolated      = which(degree(graph_farrell)==0)
graph_farrell = delete.vertices(graph_farrell, isolated)
res_farrell   = graph_vis(graph_farrell, plot=T, groups=res_wagner$communities[-isolated])
title('Farrell et. al.', line=2.5, sub=sprintf('gLasso, rho = %s', rho_farrell))
# save results
## adj matrix
wi_farrell    = ggm_farrell$model$wi %>% .[-isolated, -isolated]
colnames(wi_farrell) = rownames(wi_farrell) = names(V(graph_farrell))
file.path(tidy_farrell, sprintf('wi_adj_%s_%s.txt', rho_farrell, rho_wagner)) %>%
    fwrite(wi_farrell, .)
## gene communities
comm_farrell  = res_farrell$communities
comm_farr_dt  = data.table(GENE=names(comm_farrell), community=comm_farrell) %>%
    setkey(community)
file.path(tidy_farrell, sprintf('gene_communities_%s_%s.txt', rho_farrell, rho_wagner)) %>%
    fwrite(comm_farr_dt, .)
```

## Session Info
```{r sess, message=FALSE, warning=FALSE, paged.print=FALSE, include = FALSE}

```
