---
title: "Preprocessing Zebrafish Datasets"
author:
- name: Elyas Heidari
  affiliation:
  - Department of Biological Systems Sciences and Engineering, ETH Zurich, Switzerland 
  - IMLS Institute for Molecular Life Sciences, University of Zurich, Switzerland
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
    toc_float: true
    number_sections: false
---

<!-- 2020-07-19 10:28 -->
<!-- elihei  [<eheidari@student.ethz.ch>]-->
<!--/Volumes/Projects/scGCN/analysis/00-create-test-exp.Rmd-->

## Setup
```{r setup, include = FALSE}
library('BiocStyle')
knitr::opts_chunk$set(autodep=TRUE, cache=FALSE, dev='png', cache.lazy = FALSE)
# wflow_build(files='analysis/1-GCN_input_prep_pbmc.Rmd', view=F, verbose=T, delete_cache=F)
```



## Initialization and imports
```{r init_import}
# imports
suppressMessages(source('code/R/dep.R'))
# initialization
data_raw   = 'data_raw/pbmc'
data_exp   = 'data_raw/EXP_test'
tag_1      = 'train1'
tag_2      = 'train2'
assay_1    = file.path(data_exp, sprintf('assay_%s', tag_1))
assay_2    = file.path(data_exp, sprintf('assay_%s', tag_2))
time_stamp = format(Sys.Date(), '%Y_%m_%d')
# dirs
## read
counts_mtx_f = file.path(data_raw, 'counts.read.txt')
cell_names_f = file.path(data_raw, 'cells.read.new.txt')
gene_names_f = file.path(data_raw, 'genes.read.txt')
cell_meta_f  = file.path(data_raw, 'meta.txt')
## write
### pbmc1
counts_1_f  = file.path(assay_1, 'counts.txt')
genes_1_f   = file.path(assay_1, 'genes.txt')
cells_1_f   = file.path(assay_1, 'cells.txt')
colData_1_f = file.path(assay_1, 'colData.txt')
### pbmc2
counts_2_f  = file.path(assay_2, 'counts.txt')
genes_2_f   = file.path(assay_2, 'genes.txt') 
cells_2_f   = file.path(assay_2, 'cells.txt')
colData_2_f = file.path(assay_2, 'colData.txt')
```

## Load and wrangle input data
```{r load_input, message=FALSE, warning=FALSE, paged.print=FALSE}
# cell metadata
cell_meta    = cell_meta_f %>% fread %>% .[-1] %>% setnames('CellType', 'cell_type') %>%
    .[nGene > 1000 & percent.mito < .1] %>%
    setnames(c('NAME', 'Method'), c('id', 'batch'))
cell_meta_1  = cell_meta[Experiment == 'pbmc1']
cell_meta_2  = cell_meta[Experiment == 'pbmc2']
# count matrix
counts_mtx = counts_mtx_f %>% readMM
cell_names = cell_names_f %>% fread(header=F) %>% .$V1
gene_names = gene_names_f %>% fread(header=F) %>% .$V1
dimnames(counts_mtx) = list(gene_names, cell_names)
counts_mtx %<>% .[rowSums(.) > 100, ]
rownames(counts_mtx) %<>% limma::strsplit2(., '_') %>% .[,2] %>% tolower
counts_mtx_1 = counts_mtx %>% .[, cell_meta_1$id]
counts_mtx_2 = counts_mtx %>% .[, cell_meta_2$id]
# clean up
gc()
```

## Save results
```{r save, message=FALSE, warning=FALSE, paged.print=FALSE}
# pbmc1
counts_mtx_1 %>% writeMM(counts_1_f)
cell_meta_1  %>% fwrite(colData_1_f)
rownames(counts_mtx_1) %>% as.data.table %>% fwrite(genes_1_f)
colnames(counts_mtx_1) %>% as.data.table %>% fwrite(cells_1_f)
# pbmc2
counts_mtx_2 %>% writeMM(counts_2_f)
cell_meta_2  %>% fwrite(colData_2_f)
rownames(counts_mtx_2) %>% as.data.table %>% fwrite(genes_2_f)
colnames(counts_mtx_2) %>% as.data.table %>% fwrite(cells_2_f)
```

