---
title: "Preprocessing Zebrafish Datasets"
author:
- name: Elyas Heidari
  affiliation:
  - Department of Biological Systems Sciences and Engineering, ETH Zurich, Switzerland 
  - IMLS Institute for Molecular Life Sciences, University of Zurich, Switzerland
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
    toc_float: true
    number_sections: false
---

<!-- 2020-06-12 22:41 -->
<!-- elihei  [<eheidari@student.ethz.ch>]-->
<!--/Volumes/Projects/scGCN/analysis/1-GCN_input_prep_pbmc.Rmd-->

## Setup
```{r setup, include = FALSE}
library('BiocStyle')
knitr::opts_chunk$set(autodep=TRUE, cache=FALSE, dev='png', cache.lazy = FALSE)
# wflow_build(files='analysis/1-GCN_input_prep_pbmc.Rmd', view=F, verbose=T, delete_cache=F)
```

## Initialization and imports
```{r init_import}
# imports
suppressMessages(source('code/R/dep.R'))
library('biomaRt')
# initialization
data_raw   = 'data_raw/human_mouse'
data_tidy  = 'data_tidy/human_mouse'
out_dir    = 'output/human_mouse'
time_stamp = format(Sys.Date(), '%Y_%m_%d')
data_input = sprintf('data_input/mm_%s', time_stamp)
dir.create(data_input)
dir.create(data_tidy)
dir.create(out_dir)
## penalization parameters
rho_h    = 0.1
rho_t    = 0.1
max_mito = 10
min_counts_cell  = 1000
min_counts_gene  = 100
min_cells   = 300

# dirs
## read
counts_mtx_f = file.path(data_raw, 'mouse_counts.mtx')
gene_names_f = file.path(data_raw, 'gene_names_mouse.tsv')
cell_meta_f  = file.path(data_raw, 'mouse_metadata.tsv')
## write
### analysis data
wi_h_f  = file.path(data_tidy, sprintf('wi_adj_h_%s_%s.txt', rho_h, time_stamp))
comm_dt_1_f = file.path(data_tidy, sprintf('gene_communities_h_%s_%s.txt', rho_h, time_stamp))
wi_t_f  = file.path(data_tidy, sprintf('wi_adj_t_%s_%s.txt', rho_t, time_stamp))
comm_dt_2_f = file.path(data_tidy, sprintf('gene_communities_t_%s_%s.txt', rho_t, time_stamp))
### train data
adj_f         = file.path(data_input, 'adj.txt')
train_X_f     = file.path(data_input, 'data_train.txt')
train_X_bin_f = file.path(data_input, 'data_train_bin.txt')
train_y_f     = file.path(data_input, 'classes_train.txt')
test_X_f      = file.path(data_input, 'data_test.txt')
test_X_bin_f  = file.path(data_input, 'data_test_bin.txt')
test_y_f      = file.path(data_input, 'classes_test.txt')
### output
graph_h_f = file.path(out_dir, sprintf('graph_h_%s.pdf', time_stamp))
graph_t_f   = file.path(out_dir, sprintf('graph_t_%s.pdf', time_stamp))
```



## Load input data
```{r load_input, message=FALSE, warning=FALSE, paged.print=FALSE}
# cell metadata
cell_meta    = cell_meta_f %>% fread %>% 
    setnames(c('condition', 'rep', 'lib', 'barcode', 'batch', 'nCounts',
        'mito_pct', ' Immgen_type', 'cell_type', 'sub_type', 'x', 'y')) %>%
    # .[nCounts > min_counts_cell & mito_pct < max_mito] %>%
    .[, condition := ifelse(condition == 't', 'tumor', 'healthy')] %>%
    .[, cell_id   := paste(lib, barcode, sep=':')] 
    # %>%
    # setkey(cell_id)
# count matrix
counts_mtx = counts_mtx_f %>% readMM %>% t
cell_names = cell_meta$cell_id
gene_names = gene_names_f %>% fread(header=F) %>% .$V1
dimnames(counts_mtx) = list(gene_names, cell_names)
rownames(counts_mtx) %<>% tolower
counts_mtx %<>% .[-grep('mt-', rownames(.)),] %>%
    .[rowSums(.) > min_counts_gene, ]
cell_meta  %<>% .[nCounts > min_counts_cell & mito_pct < max_mito]
counts_mtx %<>% .[, cell_meta$cell_id]
cell_meta_1  = cell_meta[condition == 'healthy']
cell_meta_2  = cell_meta[condition == 'tumor']
# clean up
gc()
```

```{r ex, message=FALSE, warning=FALSE, paged.print=FALSE}
mart = useMart('ensembl', dataset='mmusculus_gene_ensembl', host='www.ensembl.org')

go_cellcycle = getBM(
    attributes = c('ensembl_gene_id','external_gene_name'), 
    filters    = 'go', 
    values     = 'GO:0007049', 
    mart       = mart)

go_translation = getBM(
    attributes = c('ensembl_gene_id','external_gene_name'), 
    filters    = 'go', 
    values     = 'GO:0006412', 
    mart       = mart)

go_ribosome = getBM(
    attributes = c('ensembl_gene_id','external_gene_name'), 
    filters    = 'go', 
    values     = 'GO:0005840', 
    mart       = mart)

ex_genes = unique(c(
    go_cellcycle$external_gene_name, 
    go_translation$external_gene_name, 
    go_ribosome$external_gene_name)) %>% tolower

counts_mtx %<>% .[-which(rownames(.) %in% ex_genes),]
gc()
```

## Select cell types
```{r select, message=FALSE, warning=FALSE, paged.print=FALSE}
# compute cell type frequencies
cmp_h = table(cell_meta_1$cell_type)
cmp_t = table(cell_meta_2$cell_type)
# Select cell types with > 2000 samples within pbmc 1
cmp_h = ifelse(cmp_h > 200, cmp_h, 0)
# cmp_h['CD14+ monocyte'] = 0
meta_sub_1 = cell_meta_1  %>%
    .[, .SD[sample(1:dim(.SD)[1], 
    min(min(min_cells, ..cmp_h[cell_type]), ..cmp_h[cell_type]*..cmp_h[cell_type]))], by = 'cell_type']
meta_sub_2 = cell_meta_2 %>%
    .[, .SD[sample(1:dim(.SD)[1],
    min(..cmp_t[cell_type], ..cmp_t[cell_type]*..cmp_h[cell_type]))], by = 'cell_type']
cmp_h = table(meta_sub_1$cell_type)
cmp_t = table(meta_sub_2$cell_type)
comp_all  = cbind(names(cmp_h), cmp_h, cmp_t) %>%
    as.data.table %>%
    setnames(c('type', 'h', 't'))
comp_all
# subset count matrix based on cell types
counts_mtx_1 = counts_mtx %>% .[, meta_sub_1$cell_id]
counts_mtx_2 = counts_mtx %>% .[, meta_sub_2$cell_id]
# remove redundant objects
# rm(counts_mtx)
# rm(cell_meta)
# clean up
gc()
```

<!-- ```{r hetmaps_1, message=FALSE, warning=FALSE, paged.print=FALSE}
hm_comp = comp_all %>% melt(., id.vars='type') %>%
    ggplot +
    aes(x=variable, y=type, fill=as.numeric(value)) +
    geom_tile() +
    theme_bw() +
    scale_fill_viridis(discrete=FALSE) 

comp_all %>% ggplot +
    aes()
``` -->


## Normalizaiton
```{r norm, message=FALSE, warning=FALSE, paged.print=FALSE}
# +1 --> log2 --> 0-1 rescale (cells)
sce1 = SingleCellExperiment(assays=list(counts=counts_mtx_1))
norm_mtx_1 = logNormCounts(sce1) %>% counts 
sce2 = SingleCellExperiment(assays=list(counts=counts_mtx_2))
norm_mtx_2 = logNormCounts(sce2) %>% counts 

# norm_mtx_1 = counts_mtx_1 %>% `+`(1) %>% log2 %>% apply(., 2, rescale)
# norm_mtx_2 = counts_mtx_2 %>% `+`(1) %>% log2 %>% apply(., 2, rescale)
# clean up
gc()
```

## Select highly variable genes
```{r hvg, message=FALSE, warning=FALSE, paged.print=FALSE}
# select higly variable genes
gene_vars_1 = modelGeneVar(as.matrix(norm_mtx_1))
hvg1 = getTopHVGs(gene_vars_1) %>% .[1:400]
gene_vars_2 = modelGeneVar(as.matrix(norm_mtx_2))
hvg2 = getTopHVGs(gene_vars_2) %>% .[1:400]
hvg  = intersect(hvg1, hvg2)
# subset t: genes
data_t = t(norm_mtx_2[hvg,])
const_cols = which(colSds(as.matrix(data_t)) == 0)
data_t %<>% as.data.table %>% .[, -..const_cols] 
# subset h: genes
data_h = t(norm_mtx_1[hvg,])
data_h %<>% as.data.table %>% .[, -..const_cols]
# remove redundant objects
# rm(norm_mtx_1)
# rm(norm_mtx_2)
# clean up
gc() 
```

## The GGM 
```{r ggm, message=FALSE, warning=FALSE, paged.print=FALSE}
# pbmc 1
## penalization parameter
ggm_h   = ggm(data_h, rho=rho_h, threshold =.05)
## exclude isolated nodes
graph_h = ggm_h$graph
isolated_1  = which(degree(graph_h) == 0)
graph_h = delete.vertices(graph_h, isolated_1)
## graph weights
wi_h    = ggm_h$model$wi %>% .[-isolated_1, -isolated_1]
colnames(wi_h) = rownames(wi_h) = names(V(graph_h))
diag(wi_h) = 0
## visualize graph
# graph_h_f %>% pdf(width=5, height=5)
res_h   = graph_vis(graph_h, plot=T)
title('(A) PBMC 1', line=2.5, sub=sprintf('gLasso, rho = %s', rho_h))
# dev.off()
## extract graph communities
comm_h  = res_h$communities
comm_dt_1   = data.table(GENE=names(comm_h), community=comm_h) %>%
    setkey(community)
# pbmc 2
## construct ggm
keep_genes  = names(V(graph_h))
ggm_t   = ggm(data_t[, ..keep_genes], rho=rho_t, threshold = .05)
## exclude isolated nodes
graph_t = ggm_t$graph
isolated_2  = which(degree(graph_t)==0)
graph_t = delete.vertices(graph_t, isolated_2)
## graph weights
wi_t    = ggm_t$model$wi %>% .[-isolated_2, -isolated_2]
diag(wi_t) = 0
colnames(wi_t) = rownames(wi_t) = names(V(graph_t))
## visualize graph
# graph_t_f %>% pdf(width=5, height=5)
res_t   = graph_vis(graph_t, plot=T, groups=res_h$communities[-isolated_2])
title('(B) PBMC 2', line=2.5, sub=sprintf('gLasso, rho = %s', rho_t))
# dev.off()
## extract graph communities
comm_t  = res_t$communities
comm_dt_2   = data.table(GENE=names(comm_t), community=comm_t) %>%
    setkey(community)
# subset data: exclude isolated genes
data_h %<>% as.matrix %>% .[, -isolated_1] 
data_t %<>% as.matrix %>% .[, -isolated_1]
```
<!-- ```{r graph_comp, message=FALSE, warning=FALSE, paged.p rint=FALSE}
adj_1 = ifelse(wi_h != 0, 1, 0) 
adj_2 = ifelse(wi_t != 0, 1, 0) 
``` -->

## UMAPs
```{r umaps, message=FALSE, warning=FALSE, paged.print=FALSE}
# h
umap_h = uwot::umap(data_h) 
meta_sub_1[, c('umap1', 'umap2') := list(..umap_h[,1], ..umap_h[,2])]
plot_h = meta_sub_1 %>%
    ggplot(.) +
    aes(umap1, umap2, color=cell_type) +
    geom_point(alpha=0.2) +
    theme_bw() + 
    theme(axis.text= element_blank()) +
    scale_color_brewer(palette="Dark2") +
    labs(title='h et al.')
# t 
umap_t  = uwot::umap(data_t) 
meta_sub_2[, c('umap1', 'umap2') := list(..umap_t[,1], ..umap_t[,2])]
plot_t  = meta_sub_2 %>%
    ggplot(.) +
    aes(umap1, umap2, color=cell_type) +
    geom_point(alpha = 0.2) +
    theme_bw() + 
    theme(axis.text = element_blank()) +
    scale_color_brewer(palette="Dark2") +
    # scale_fill_manual(colorRampPalette(brewer.pal(12, "Accent"))(12)) +
    labs(title='t et al.')
# draw
(plot_t + plot_h) + plot_layout(guides = 'collect')
``` 

## Save results
```{r save, message=FALSE, warning=FALSE, paged.print=FALSE}
# analysis data
## pbmc 1
wi_h_f  %>% fwrite(wi_h, .)
comm_dt_1_f %>% fwrite(comm_dt_1, .)
## t
wi_t_f  %>% fwrite(wi_t, .)
comm_dt_2_f %>% fwrite(comm_dt_2, .)
# train & test data
adj_f     %>% fwrite(data.table(ifelse(abs(wi_h) > 0.05, 1, 0)), .)
# adj_f     %>% fwrite(data.table(abs(wi_h)), .)
order_train = order(meta_sub_1$cell_type)
train_X_f %>% fwrite(data.table(t(data_h[order_train,])), .)
train_X_bin_f %>% fwrite(data.table(ifelse(t(data_h[order_train,]) > 10, 1, 0)), .)
train_y_f %>% fwrite(meta_sub_1[order_train], .)
order_test  = order(meta_sub_2$cell_type)
test_X_f  %>% fwrite(data.table(t(data_t[order_test,])), .)
test_X_bin_f %>% fwrite(data.table(ifelse(t(data_t[order_test,]) > 10, 1, 0)), .)
test_y_f  %>% fwrite(meta_sub_2[order_test,], .)
```