---
title: "Preprocessing Zebrafish Datasets"
author:
- name: Elyas Heidari
  affiliation:
  - Department of Biological Systems Sciences and Engineering, ETH Zurich, Switzerland 
  - IMLS Institute for Molecular Life Sciences, University of Zurich, Switzerland
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
    toc_float: true
    number_sections: false
---

<!-- 2020-07-06 08:57 -->
<!-- elihei  [<eheidari@student.ethz.ch>]-->
<!--/Volumes/Projects/scGCN/analysis/02-GCN_output_pbmc.rmd-->

## Setup
```{r setup, include = FALSE}
library('BiocStyle')
knitr::opts_chunk$set(autodep=TRUE, cache=FALSE, dev='png', cache.lazy = FALSE)
# wflow_build(files='analysis/1-GCN_input_prep_pbmc.Rmd', view=F, verbose=T, delete_cache=F)
```

## Initialization and imports
```{r init_import}
# imports
suppressMessages(source('code/R/dep.R'))
# initialization
data_raw   = 'data_raw/pbmc'
data_tidy  = 'data_tidy/pbmc'
data_train = 'data_input/pbmc_test'
model_dir  = 'models/pbmc_test'
out_dir    = 'output/pbmc'
time_stamp = format(Sys.Date(), '%Y_%m_%d')
# dirs
## node embeddings
train_layer = file.path(model_dir, 'train_layer_')
test_layer  = file.path(model_dir, 'test_layer_')
## labels
train_label = file.path(data_train, 'classes_train.txt')
test_label  = file.path(data_train, 'classes_test.txt')
## write
### plots
umap_out    = file.path(out_dir, sprintf('layer_umaps_pbmc_%s.png', time_stamp))
```

## Load input data
```{r read, message=FALSE, warning=FALSE, paged.print=FALSE}
# data train
# indices
train_idx    = 'data_input/pbmc_test/train_idx.txt' %>% fread %>% .$V1 %>% `+`(1)
test_idx     = 'data_input/pbmc_test/test_idx.txt'  %>% fread %>% .$V1 %>% `+`(1)
# labels
train_cell_types = train_label %>% fread %>% .$cell_type %>% .[train_idx]
test_cell_types  = test_label  %>% fread %>% .$cell_type %>% .[test_idx]
train_Methods = train_label %>% fread %>% .$Method %>% .[train_idx]
test_Methods  = test_label  %>% fread %>% .$Method %>% .[test_idx]
# node embeddings
train_layers = 1:3 %>% 
    map(~ fread(sprintf('%s%s.csv', train_layer, .x), header=T)) %>%
    map(~ t(as.matrix(.x[, -1]))) 
test_layers  = 1:3 %>% 
    map(~ fread(sprintf('%s%s.csv', test_layer, .x), header=T)) %>%
    map(~ t(as.matrix(.x[, -1])))

```


## UMAPs
```{r umaps, message=FALSE, warning=FALSE, paged.print=FALSE}
plot_umap <- function(mtx, labels, shapes, title){
    umap_df = uwot::umap(mtx) 
    umap_dt = data.table(dataset=factor(shapes), cell_type=factor(labels), umap1=umap_df[,1], umap2=umap_df[,2]) %>%
        .[sample(1:dim(.)[1], 1000)]
    umap_dt %>%
        ggplot +
        aes(umap1, umap2, color=cell_type, shape=dataset) +
        geom_point(size=2) +
        theme_bw() + 
        theme(axis.text= element_blank()) +
        scale_color_brewer(palette="Dark2") +
        scale_shape_manual(values = c(1, 4)) +
        labs(title=title)
}
train_cell_types = ifelse(train_cell_types == 'B cell' , 'temp', train_cell_types)
train_cell_types = ifelse(train_cell_types == 'Cytotoxic T cell' , 'B cell', train_cell_types)
train_cell_types = ifelse(train_cell_types == 'temp' , 'Cytotoxic T cell', train_cell_types)
train_cell_types = ifelse(train_cell_types == 'Cytotoxic T cell' , 'temp', train_cell_types)
train_cell_types = ifelse(train_cell_types == 'CD4+ T cell' , 'Cytotoxic T cell', train_cell_types)
train_cell_types = ifelse(train_cell_types == 'temp' , 'CD4+ T cell', train_cell_types)

layers = 1:3 %>% map(~rbind(train_layers[[.x]], test_layers[[.x]]))
labels = c(train_cell_types, test_cell_types)
shapes = c(rep('training', length(train_cell_types)), rep('test', length(test_cell_types)))
umaps  = 1:3 %>% map(~ plot_umap(layers[[.x]], labels, shapes, paste('layer', .x)))

umap_plt    = (umaps[[1]] + umaps[[2]] + umaps[[3]]) +
    plot_layout(guides = 'collect')

    train_umaps = 1:3 %>% 
    map(~ plot_umap(train_layers[[.x]], train_labels, paste('train, layer', .x)))
test_umaps  = 1:3 %>%
    map(~ plot_umap(test_layers[[.x]], test_labels, paste('test, layer', .x)))
umap_plt    = (train_umaps[[1]] + train_umaps[[2]] + train_umaps[[3]]) / 
    (test_umaps[[1]] + test_umaps[[2]] + test_umaps[[3]]) + 
    plot_layout(guides = 'collect')
```






##t-SNEs
```{r tsne, message=FALSE, warning=FALSE, paged.print=FALSE}
plot_tsne <- function(mtx, labels, title){
    tsne_df = Rtsne(mtx, perplexity= 50)$Y
    tsne_dt = data.table(Method=factor(labels), tsne1=tsne_df[,1], tsne2=tsne_df[,2])
    plot_pbmc1 = tsne_dt %>%
        ggplot +
        aes(tsne1, tsne2, color=Method) +
        geom_point(alpha=0.2) +
        theme_bw() + 
        theme(axis.text= element_blank()) +
        scale_color_brewer(palette="Dark2") +
        labs(title=title)
}

train_tsnes = 1:3 %>% 
    map(~ plot_tsne(train_layers[[.x]], train_labels, paste('train, layer', .x)))
test_tsnes  = 1:3 %>%
    map(~ plot_tsne(test_layers[[.x]], test_labels, paste('test, layer', .x)))
tsne_plt    = (train_tsnes[[1]] + train_tsnes[[2]] + train_tsnes[[3]]) / 
    (test_tsnes[[1]] + test_tsnes[[2]] + test_tsnes[[3]]) + 
    plot_layout(guides = 'collect')

```

```{r tsne, message=FALSE, warning=FALSE, paged.print=FALSE}

```

## Save results
```{r name, message=FALSE, warning=FALSE, paged.print=FALSE}
umap_out %>% ggsave(umap_plt, filename=., device='png')
```