---
title: "Final Report: Inception GCN"
author:
- name: Elyas Heidari
  affiliation:
  - Department of Biological Systems Sciences and Engineering, ETH Zurich, Switzerland 
  - IMLS Institute for Molecular Life Sciences, University of Zurich, Switzerland
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
    toc_float: true
    number_sections: false
---
<!-- 2020-09-03 09:58 -->
<!-- elihei  [<eheidari@student.ethz.ch>]-->
<!--/Volumes/Projects/scGCN/analysis/04-final-report-GCN-2020-09-03.rmd-->

## Setup
```{r setup, include = FALSE}
library('BiocStyle')
knitr::opts_chunk$set(autodep=TRUE, cache=FALSE, dev='png', cache.lazy = FALSE)
# wflow_build(files='analysis/1-GCN_input_prep_pbmc.Rmd', view=F, verbose=T, delete_cache=F)
```

## Initialization and imports
```{r init_import}
# imports
suppressMessages(source('code/R/dep.R'))
nice_cols_1   = c(
    "#DC050C", "#FB8072", "#1965B0", "#7BAFDE", "#882E72", "#B17BA6", 
    "#FF7F00", "#FDB462", "#E7298A", "#E78AC3", "#33A02C", "#B2DF8A", 
    "#55A1B1", "#8DD3C7", "#A6761D", "#E6AB02", "#7570B3", "#BEAED4")
nice_cols_2 = c("#aa8282", "#666666", "#999999",  "#d4b7b7", "#8600bf", "#ba5ce3", 
    "#808000", "#aeae5c", "#1e90ff", "#00bfff", "#56ff0d", "#ffff00")
# initialization
data_input = 'data_input/mouse_mouse'
data_tidy  = 'data_tidy/human_mouse'
model_dir  = 'models/mouse_mouse'
out_dir    = 'output/mouse_mouse'
time_stamp = format(Sys.Date(), '%Y_%m_%d')
# dirs
## input data
adj1_f     = file.path(data_tidy, 'wi_adj_h_0.1_2020_12_08.txt')
adj2_f     = file.path(data_tidy, 'wi_adj_t_0.1_2020_12_08.txt')
train_X_f = file.path(data_input, 'data_train.txt')
train_y_f = file.path(data_input, 'classes_train.txt')
test_X_f  = file.path(data_input, 'data_test.txt')
test_y_f  = file.path(data_input, 'classes_test.txt')
comm_f    = file.path(data_tidy, 'gene_communities_h_0.1_2020_12_08.txt')
## labels
train_idx_f = file.path(data_input, 'train_idx.txt')
test_idx_f  = file.path(data_input, 'test_idx.txt')
## node embeddings
train_layers_f = file.path(model_dir, 'train_layer_')
test_layers_f  = file.path(model_dir, 'test_layer_')
## write
### plots
umap_out  = file.path(out_dir, sprintf('layer_umaps_%s_GCN.pdf', time_stamp))
graph_out = file.path(out_dir, sprintf('graph_%s_%s.pdf', '%s', time_stamp))
comm_out  = file.path(out_dir, sprintf('graph_comm_nc_%s_%s.pdf', '%s', time_stamp))
conf_out  = file.path(out_dir, sprintf('conf_%s_GCN.pdf', time_stamp))
```

## Load input data
```{r read, message=FALSE, warning=FALSE, paged.print=FALSE}
# data train
train_idx = train_idx_f %>% fread %>% .$V1 %>% `+`(1)
test_idx  = test_idx_f %>% fread %>% .$V1 %>% `+`(1)
adj1       = adj1_f %>% fread %>% as.matrix 
adj1       = ifelse(abs(adj1) > 0.05, 1, 0)
adj2       = adj2_f %>% fread %>% as.matrix 
adj2       = ifelse(abs(adj2) > 0.03, 1, 0)
diff_genes = setdiff(colnames(adj1), colnames(adj2))
adj2 = cbind(adj2, matrix(0, nrow= nrow(adj2), ncol=length(diff_genes), dimnames=list(NULL,diff_genes)))
adj2 = rbind(adj2, matrix(0, nrow= length(diff_genes), ncol=ncol(adj2), dimnames=list(diff_genes,NULL)))
rownames(adj2) = colnames(adj2)
adj2 = adj2[colnames(adj1), colnames(adj1)]
train_X   = train_X_f %>% fread %>% as.matrix %>% t %>% .[train_idx,]
train_y   = train_y_f %>% fread %>% .[train_idx] 
test_X    = test_X_f %>% fread %>% as.matrix %>% t %>% .[test_idx,]
test_y    = test_y_f %>% fread %>% .[test_idx] 
# train_y %>% .[grep('10x', Method), Method := '10x Chromium']
# test_y %>% .[grep('10x', Method), Method := '10x Chromium']
# grpah communities
graph_com = comm_f %>% fread %>% 
    .[, color := c(brewer.pal(n=7,"Dark2"), brewer.pal(n=8,"Set3"))[community]] %>%
    setkey(GENE) %>%
    .[colnames(adj1)]

# node embeddings
train_layers = 1:2 %>% 
    map(~ fread(sprintf('%s%s.csv', train_layers_f, .x), header=T)) %>%
    map(~ t(as.matrix(.x[, -1]))) 
test_layers  = 1:2 %>% 
    map(~ fread(sprintf('%s%s.csv', test_layers_f, .x), header=T)) %>%
    map(~ t(as.matrix(.x[, -1])))

```

## Graph Communities
```{r graph_com, message=FALSE, warning=FALSE, paged.print=FALSE}
graph_col_comm <- function(graph, lay, grp, sz, title=NULL, labels){
    igraph::V(graph)$color <- grp
    v <-  igraph::V(graph)
    sprintf(comm_out, title) %>% pdf()
    plot.igraph(
        graph,
        vertex.size = 6,
        layout = lay,
        vertex.label = labels,
        vertex.frame.color = igraph::V(graph)$color,
        vertex.label.family = 'Helvetica',
        vertex.label.dist = 0,
        vertex.label.cex = .25,
        vertex.label.font = .5,
        vertex.label.color = '#585c59',
        main=NULL)
    dev.off()
}

graph1  = graph_from_adjacency_matrix(adj1, 'undirected')
lay_nc1 = layout_nicely(graph1)
graph_col_comm(graph1, lay_nc1, graph_com$color, 5, title='mm1', labels=graph_com$GENE)

graph2  = graph_from_adjacency_matrix(adj2, 'undirected')
lay_nc2 = layout_nicely(graph2)
graph_col_comm(graph2, lay_nc2, graph_com$color, 5, title='mm2', labels=graph_com$GENE)
```

## Graphs
```{r graphs, message=FALSE, warning=FALSE, paged.print=FALSE}
cell_type_graph <- function(type, title){
    sprintf(graph_out, paste0(title, '_train')) %>% pdf()
    train_idx = which(train_y$cell_type == type)
    grp       = colMeans(train_X[train_idx,])
    igraph::V(graph1)$color  = rgb(0, 0, floor(255*(grp^(1/2))/max(grp^(1/2))), maxColorValue=255, alpha=255)
    plot.igraph(graph1,
        vertex.size = 5,
        layout = lay_nc1,
        vertex.frame.color = igraph::V(graph1)$color,
        vertex.label = "",
        main=title)
    dev.off()
    sprintf(graph_out, paste0(title, '_test')) %>% pdf()
    test_idx = which(test_y$cell_type == type)
    grp       = colMeans(test_X[test_idx,])
    igraph::V(graph1)$color  = rgb(0, 0, floor(255*(grp^(1/2))/max(grp^(1/2))), maxColorValue=255, alpha=255)
    plot.igraph(graph1,
    vertex.size = 5,
    layout = lay_nc1,
    vertex.label = "",
    vertex.frame.color = igraph::V(graph1)$color)
    dev.off()
}

unique(train_y$cell_type) %>% map(~cell_type_graph(.x, .x))
```

## Graphs
```{r graphs, message=FALSE, warning=FALSE, paged.print=FALSE}
cell_type_graph_layer <- function(type, title){
    sprintf(graph_out, paste0(title, '_train_layer_2')) %>% pdf()
    train_idx = which(train_y$cell_type == type)
    grp       = colMeans(train_layers[[2]][train_idx,])
    igraph::V(graph1)$color  = rgb(0, 0, floor(255*(grp^(1/2))/max(grp^(1/2))), maxColorValue=255, alpha=255)
    plot.igraph(graph1,
        vertex.size = 5,
        layout = lay_nc1,
        vertex.frame.color = igraph::V(graph1)$color,
        vertex.label = "",
        main=title)
    dev.off()
    sprintf(graph_out, paste0(title, '_test_layer_2')) %>% pdf()
    test_idx = which(test_y$cell_type == type)
    grp       = colMeans(test_layers[[2]][test_idx,])
    igraph::V(graph1)$color  = rgb(0, 0, floor(255*(grp^(1/2))/max(grp^(1/2))), maxColorValue=255, alpha=255)
    plot.igraph(graph1,
    vertex.size = 5,
    layout = lay_nc1,
    vertex.label = "",
    vertex.frame.color = igraph::V(graph1)$color)
    dev.off()
}

unique(train_y$cell_type) %>% map(~cell_type_graph_layer(.x, .x))
```


## UMAPs
```{r umaps, message=FALSE, warning=FALSE, paged.print=FALSE}
plot_umap <- function(mtx, cell_types, datasets, batches, title){
    umap_df = uwot::umap(mtx) 
    umap_dt = data.table(dataset=factor(datasets), 
                         cell_type=factor(cell_types), 
                         batch=factor(batches),
                         umap1=umap_df[,1], umap2=umap_df[,2]) 
    type_umap = umap_dt %>%
        ggplot +
        aes(umap1, umap2, color=cell_type, shape=dataset, size=dataset, pch=10, colour='black') +
        geom_point() +
        theme_void() + 
        theme(axis.text= element_blank(), 
            axis.ticks.x=element_blank(),
            axis.ticks.y=element_blank()) +
        scale_color_manual(values=nice_cols_1) +
        scale_shape_manual(values = c(1, 4)) +
        labs(title=title, x='', y='')
    batch_umap = umap_dt %>%
        ggplot +
        aes(umap1, umap2, color=batch, shape=dataset, size=dataset, pch=10) +
        geom_point() +
        theme_void() + 
        theme(axis.text= element_blank(), 
            axis.ticks.x=element_blank(),
            axis.ticks.y=element_blank()) +
        scale_color_manual(values=nice_cols_2) +
        scale_shape_manual(values = c(1, 4)) +
        labs(title='', x='', y='')
    list(type=type_umap, batch=batch_umap)
}

raw_layer  = rbind(train_X, test_X)
sub_idx    = sample(1:dim(raw_layer)[1], 3000)
# sub_idx    = 1:dim(raw_layer)[1]
cell_types = c(train_y$cell_type, test_y$cell_type)[sub_idx]
batches    = c(train_y$condition, test_y$condition)[sub_idx]
datasets   = c(rep('training', dim(train_X)[1]), rep('test', dim(test_X)[1]))[sub_idx]
umap_raw   = list(plot_umap(raw_layer[sub_idx,], cell_types, datasets, batches, 'raw data'))

raw_layer  = list(rbind(train_X, test_X))
layers = 1:2 %>% map(~rbind(train_layers[[.x]], test_layers[[.x]]))
umaps  = 1:2 %>% map(~ plot_umap(layers[[.x]][sub_idx,], cell_types, datasets, batches, paste('layer', .x)))
umaps  = append(umap_raw, umaps)
umap_plt    =  (umaps[[1]]$type + umaps[[2]]$type + umaps[[3]]$type  +
    umaps[[1]]$batch + umaps[[2]]$batch + umaps[[3]]$batch ) +
    plot_layout(guides = 'collect', nrow=2)
```



```{r heatmaps, message=FALSE, warning=FALSE, paged.print=FALSE}
hm_conf <- function(dt, acc, dat){
    melt(dt, id.vars='type') %>%
        .[, `row scaled freq.` := value/sum(value), by= 'variable'] %>%
        ggplot +
        aes(x=type, y=variable, fill=`row scaled freq.`) +
        geom_tile(colour = "white") +
        geom_text(aes(label=value), colour = "white") +
        theme_void()+
        theme(axis.ticks= element_blank()) +
        labs(y='True cell type', x='Predicted cell type', title=sprintf('%s accuracy = %s', dat, acc))
}

cell_types = c('B', 'CD14+', 'CD16+', 'CD4+', 'Cyto', 'Dend.', 'Mega.', 'NK')
train_dt = data.table(type=cell_types, 
        `B`     = c(146, 1, 0, 1, 1, 1, 0, 0),
        `CD14+` = c(0, 131, 6, 2, 2, 4, 5, 0),
        `CD16+` = c(0, 4, 143, 0, 1, 1, 1, 0),
        `CD4+`  = c(0, 3, 1, 116, 23, 1, 0, 6),
        `Cyto.` = c(2, 2, 1, 16, 115, 0, 1, 13),
        `Dend.` = c(0, 3, 0, 1, 0, 145, 0, 1),
        `Mega.` = c(1, 2, 0, 1, 2, 0, 144, 0),
        `NK`    = c(0, 0, 0, 2, 12, 1, 0, 135))
conf_trian = train_dt %>% hm_conf(acc=0.896, dat='training')
test_dt = data.table(type=cell_types, 
        `B`     = c(2403, 13, 0, 4, 5, 17, 8, 0),
        `CD14+` = c(2, 1328, 18, 1, 5, 225, 3, 0),
        `CD16+`  = c(0, 40, 173, 1, 0, 15, 1, 0),
        `CD4+`  = c(40, 24, 3, 2531, 196, 3, 35, 0),
        `Cyto.`  = c(28, 18, 0, 188, 1734, 2, 19, 125),
        `Dend.` = c(9, 46, 1, 0, 1, 148, 2, 0),
        `Mega.` = c(0, 7, 0, 0, 3, 0, 51, 0),
        `NK`   = c(2, 5, 1, 0, 142, 7, 4, 530))
conf_test = test_dt %>% hm_conf(acc=0.875, dat='test')
conf_hm   = conf_trian + conf_test +
    plot_layout(guides = 'collect')

Epoch 31:
train: loss=0.001, acc=0.928
test: loss=0.000, acc=0.863
---------------
train confusion matrix:
 [[149   1   0   0   0   0   0   0]
 [  0 146   0   0   1   1   2   0]
 [  0   0 150   0   0   0   0   0]
 [  0   1   0 124  24   0   0   1]
 [  1   1   0   7 141   0   0   0]
 [  0   2   0   0   0 148   0   0]
 [  0   0   0   0   0   0 150   0]
 [  0   0   0   3  41   1   0 105]]
test confusion matrix:
 [[2415    1    0   20    8    4    2    0]
 [  43 1322   19    8    3  181    6    0]
 [   7   22  195    0    3    1    2    0]
 [  24   18    0 2576  207    0    6    1]
 [  22    6    0  449 1533    0    8   96]
 [  33   15    0    0    1  156    2    0]
 [   0    7    0    1    1    1   51    0]
 [   3    0    0    3  159    0    0  526]]
                                                               
#  [  36   26  547 1505]]  
```

## Save results
```{r name, message=FALSE, warning=FALSE, paged.print=FALSE}
umap_out %>% ggsave(umap_plt, filename=., width=15, height=7, device='pdf')
conf_out %>% ggsave(conf_hm, filename=., width=11, height=5, device='pdf')
```