---
title: "Final Report: Inception GCN"
author:
- name: Elyas Heidari
  affiliation:
  - Department of Biological Systems Sciences and Engineering, ETH Zurich, Switzerland 
  - IMLS Institute for Molecular Life Sciences, University of Zurich, Switzerland
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output:
  workflowr::wflow_html:
    code_folding: hide
    toc: true
    toc_float: true
    number_sections: false
---
<!-- 2020-09-03 09:58 -->
<!-- elihei  [<eheidari@student.ethz.ch>]-->
<!--/Volumes/Projects/scGCN/analysis/04-final-report-GCN-2020-09-03.rmd-->

## Setup
```{r setup, include = FALSE}
library('BiocStyle')
knitr::opts_chunk$set(autodep=TRUE, cache=FALSE, dev='png', cache.lazy = FALSE)
# wflow_build(files='analysis/1-GCN_input_prep_pbmc.Rmd', view=F, verbose=T, delete_cache=F)
```


## Initialization and imports
```{r init_import}
# imports
suppressMessages(source('code/R/dep.R'))
# initialization
data_input = 'data_input/pbmc_2020_09_01'
data_tidy  = 'data_tidy/pbmc'
model_dir  = 'models/pbmc_2020_11_12/models/pbmc'
out_dir    = 'output/pbmc_2020_11_12'
time_stamp = format(Sys.Date(), '%Y_%m_%d')
# dirs
## input data
adj1_f     = file.path(data_tidy, 'wi_adj_pbmc1_0.1_2020_09_01.txt')
adj2_f     = file.path(data_tidy, 'wi_adj_pbmc2_0.1_2020_09_01.txt')
train_X_f = file.path(data_input, 'data_train.txt')
train_y_f = file.path(data_input, 'classes_train.txt')
test_X_f  = file.path(data_input, 'data_test.txt')
test_y_f  = file.path(data_input, 'classes_test.txt')
comm_f    = file.path(data_tidy, 'gene_communities_pbmc1_0.1_2020_09_01.txt')
## labels
train_idx_f = file.path(data_input, 'train_idx_GCN.txt')
test_idx_f  = file.path(data_input, 'test_idx_GCN.txt')
## node embeddings
train_layers_f = file.path(model_dir, 'train_layer_')
test_layers_f  = file.path(model_dir, 'test_layer_')
## write
### plots
umap_out  = file.path(out_dir, sprintf('layer_umaps_%s_GCN.pdf', time_stamp))
graph_out = file.path(out_dir, sprintf('graph_%s_%s.pdf', '%s', time_stamp))
comm_out  = file.path(out_dir, sprintf('graph_comm_nc_%s_%s.pdf', '%s', time_stamp))
conf_out  = file.path(out_dir, sprintf('conf_%s_GCN.pdf', time_stamp))
```

## Load input data
```{r read, message=FALSE, warning=FALSE, paged.print=FALSE}
# data train
train_idx = train_idx_f %>% fread %>% .$V1 %>% `+`(1)
test_idx  = test_idx_f %>% fread %>% .$V1 %>% `+`(1)
adj1       = adj1_f %>% fread %>% as.matrix 
adj1       = ifelse(abs(adj1) > 0.08, 1, 0)
adj2       = adj2_f %>% fread %>% as.matrix 
adj2       = ifelse(abs(adj2) > 0.07, 1, 0)
diff_genes = setdiff(colnames(adj1), colnames(adj2))
adj2 = cbind(adj2, matrix(0, nrow= nrow(adj2), ncol=length(diff_genes), dimnames=list(NULL,diff_genes)))
adj2 = rbind(adj2, matrix(0, nrow= length(diff_genes), ncol=ncol(adj2), dimnames=list(diff_genes,NULL)))
rownames(adj2) = colnames(adj2)
adj2 = adj2[colnames(adj1), colnames(adj1)]
train_X   = train_X_f %>% fread %>% as.matrix %>% t %>% .[train_idx,]
train_y   = train_y_f %>% fread %>% .[train_idx] 
test_X    = test_X_f %>% fread %>% as.matrix %>% t %>% .[test_idx,]
test_y    = test_y_f %>% fread %>% .[test_idx] 
train_y %>% .[grep('10x', Method), Method := '10x Chromium']
test_y %>% .[grep('10x', Method), Method := '10x Chromium']
# grpah communities
graph_com = comm_f %>% fread %>% 
    .[, color := c(brewer.pal(n=7,"Dark2"), brewer.pal(n=8,"Set3"))[community]] %>%
    setkey(GENE) %>%
    .[colnames(adj1)]

# node embeddings
train_layers = 1:3 %>% 
    map(~ fread(sprintf('%s%s.csv', train_layers_f, .x), header=T)) %>%
    map(~ t(as.matrix(.x[, -1]))) 
test_layers  = 1:3 %>% 
    map(~ fread(sprintf('%s%s.csv', test_layers_f, .x), header=T)) %>%
    map(~ t(as.matrix(.x[, -1])))
```


## Graphs
```{r graphs, message=FALSE, warning=FALSE, paged.print=FALSE}
idx = which(train_y$cell_type == 'CD14+ monocyte' | train_y$cell_type == 'CD16+ monocyte')
ggm_1   = ggm(data.table(train_layers[[1]])[idx], rho=0.2, threshold = 0.1)
## exclude isolated nodes
graph_1 = ggm_1$graph
isolated_1  = which(degree(graph_1) == 0)
graph_1 = delete.vertices(graph_1, isolated_1)
## graph weights
wi_1    = ggm_1$model$wi %>% .[-isolated_1, -isolated_1]
colnames(wi_1) = rownames(wi_1) = names(V(graph_1))
diag(wi_1) = 0

adj_test = ifelse(abs(wi_1) > 0.1, 1, 0)
graph1  = graph_from_adjacency_matrix(adj_test, 'undirected')
lay_nc1 = layout_nicely(graph1)
graph_col_comm(graph1, lay_nc1, 'cyan', 5, title='train1', labels=graph_com$GENE)  
```

## Graphs
```{r graphs, message=FALSE, warning=FALSE, paged.print=FALSE}
idx = which(train_y$cell_type == 'CD14+ monocyte' | train_y$cell_type == 'CD16+ monocyte')
ggm_1   = ggm(data.table(train_layers[[2]])[idx], rho=0.2, threshold = 0.1)
## exclude isolated nodes
graph_1 = ggm_1$graph
isolated_1  = which(degree(graph_1) == 0)
graph_1 = delete.vertices(graph_1, isolated_1)
## graph weights
wi_1    = ggm_1$model$wi %>% .[-isolated_1, -isolated_1]
colnames(wi_1) = rownames(wi_1) = names(V(graph_1))
diag(wi_1) = 0

adj_test = ifelse(abs(wi_1) > 0.1, 1, 0)
graph1  = graph_from_adjacency_matrix(adj_test, 'undirected')
lay_nc1 = layout_nicely(graph1)
graph_col_comm(graph1, lay_nc1, 'cyan', 5, title='train2', labels=graph_com$GENE)   
```

## Graphs
```{r graphs, message=FALSE, warning=FALSE, paged.print=FALSE}
idx = which(train_y$cell_type == 'CD14+ monocyte' | train_y$cell_type == 'CD16+ monocyte')
ggm_1   = ggm(data.table(train_layers[[3]])[idx], rho=0.2, threshold = 0.1)
## exclude isolated nodes
graph_1 = ggm_1$graph
isolated_1  = which(degree(graph_1) == 0)
graph_1 = delete.vertices(graph_1, isolated_1)
## graph weights
wi_1    = ggm_1$model$wi 
# %>% .[-isolated_1, -isolated_1]
colnames(wi_1) = rownames(wi_1) = names(V(graph_1))
diag(wi_1) = 0

adj_test = ifelse(abs(wi_1) > 0.1, 1, 0)
graph1  = graph_from_adjacency_matrix(adj_test, 'undirected')
lay_nc1 = layout_nicely(graph1)
graph_col_comm(graph1, lay_nc1, 'cyan', 5, title='train31', labels=graph_com$GENE)   
```

## Graphs
```{r graphs, message=FALSE, warning=FALSE, paged.print=FALSE}
idx = grepl('T cell', train_y$cell_type)
ggm_1   = ggm(data.table(train_layers[[3]])[idx], rho=0.2, threshold = 0.1)
## exclude isolated nodes
graph_1 = ggm_1$graph
isolated_1  = which(degree(graph_1) == 0)
graph_1 = delete.vertices(graph_1, isolated_1)
## graph weights
wi_1    = ggm_1$model$wi %>% .[-isolated_1, -isolated_1]
colnames(wi_1) = rownames(wi_1) = names(V(graph_1))
diag(wi_1) = 0

adj_test = ifelse(abs(wi_1) > 0.1, 1, 0)
graph1  = graph_from_adjacency_matrix(adj_test, 'undirected')
lay_nc1 = layout_nicely(graph1)
graph_col_comm(graph1, lay_nc1, 'cyan', 5, title='train32', labels=graph_com$GENE)   
```

## Graph Communities
```{r graph_com, message=FALSE, warning=FALSE, paged.print=FALSE}
graph_col_comm <- function(graph, lay, grp, sz, title=NULL, labels){
    igraph::V(graph)$color <- grp
    v <-  igraph::V(graph)
    sprintf(comm_out, title) %>% pdf()
    plot.igraph(
        graph,
        vertex.size = 6,
        layout = lay,
        vertex.label = labels,
        vertex.frame.color = igraph::V(graph)$color,
        vertex.label.family = 'Helvetica',
        vertex.label.dist = 0,
        vertex.label.cex = .25,
        vertex.label.font = .5,
        vertex.label.color = '#585c59',
        main=NULL)
    dev.off()
}

graph1  = graph_from_adjacency_matrix(adj1, 'undirected')
lay_nc1 = layout_nicely(graph1)
graph_col_comm(graph1, lay_nc1, graph_com$color, 5, title='pbmc1', labels=graph_com$GENE)

graph2  = graph_from_adjacency_matrix(adj2, 'undirected')
lay_nc2 = layout_nicely(graph2)
graph_col_comm(graph2, lay_nc2, graph_com$color, 5, title='pbmc2', labels=graph_com$GENE)
```




## UMAPs
```{r umaps, message=FALSE, warning=FALSE, paged.print=FALSE}
plot_umap <- function(mtx, cell_types, datasets, batches, title){
    umap_df = uwot::umap(mtx) 
    umap_dt = data.table(dataset=factor(datasets), 
                         cell_type=factor(cell_types), 
                         batch=factor(batches),
                         umap1=umap_df[,1], umap2=umap_df[,2]) 
    type_umap = umap_dt %>%
        ggplot +
        aes(umap1, umap2, color=cell_type, shape=dataset, size=dataset, pch=10, colour='black') +
        geom_point() +
        theme_bw() + 
        theme(axis.text= element_blank(), 
            axis.ticks.x=element_blank(),
            axis.ticks.y=element_blank()) +
        scale_color_brewer(palette='Dark2') +
        scale_shape_manual(values = c(1, 4)) +
        labs(title=title, x='', y='')
    batch_umap = umap_dt %>%
        ggplot +
        aes(umap1, umap2, color=batch, shape=dataset, size=dataset, pch=10) +
        geom_point() +
        theme_bw() + 
        theme(axis.text= element_blank(), 
            axis.ticks.x=element_blank(),
            axis.ticks.y=element_blank()) +
        scale_color_brewer(palette='Set3') +
        scale_shape_manual(values = c(1, 4)) +
        labs(title='', x='', y='')
    list(type=type_umap, batch=batch_umap)
}

raw_layer  = rbind(train_X, test_X)
sub_idx    = sample(1:dim(raw_layer)[1], 3000)
# sub_idx    = 1:dim(raw_layer)[1]
cell_types = c(train_y$cell_type, test_y$cell_type)[sub_idx]
batches    = c(train_y$Method, test_y$Method)[sub_idx]
datasets   = c(rep('training', dim(train_X)[1]), rep('test', dim(test_X)[1]))[sub_idx]
umap_raw   = list(plot_umap(raw_layer[sub_idx,], cell_types, datasets, batches, 'raw data'))

raw_layer  = list(rbind(train_X, test_X))
layers = 1:3 %>% map(~rbind(train_layers[[.x]], test_layers[[.x]]))
umaps  = 1:3 %>% map(~ plot_umap(layers[[.x]][sub_idx,], cell_types, datasets, batches, paste('layer', .x)))
umaps  = append(umap_raw, umaps)
umap_plt    =  (umaps[[1]]$type + umaps[[2]]$type + umaps[[3]]$type + umaps[[4]]$type +
    umaps[[1]]$batch + umaps[[2]]$batch + umaps[[3]]$batch + umaps[[4]]$batch) +
    plot_layout(guides = 'collect', nrow=2)
```


